Document: usch
Title: Debian usch Manual
Author: <insert document author here>
Abstract: This manual describes what usch is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/usch/usch.sgml.gz

Format: postscript
Files: /usr/share/doc/usch/usch.ps.gz

Format: text
Files: /usr/share/doc/usch/usch.text.gz

Format: HTML
Index: /usr/share/doc/usch/html/index.html
Files: /usr/share/doc/usch/html/*.html
